/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("KotlinBVOD.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("com.beust:klaxon:5.5")
}

application {
    // Define the main class for the application.
    mainClass.set("KotlinBVOD.app.AppKt")
}
